### ISSUE TITLE
QuickTree Bug [Not Fixed]

### ISSUE THREAD

**Issue by GunsNHemps** [Pozzoo/quickTreePlugin#2]
I have a problem with the QuickTree plugin, the tree that falldown still laying on the exact spot but can't remove anything also not with WorldEdit? I have no recent backup of the server so much progress will be lost if it can't be fixed.

![image](https://github.com/Pozzoo/quickTreePlugin/assets/173932802/31f7b730-b242-447d-bcea-eb8964095bb7)

**Comment by Pozzoo** [comment]
Hello, I have a few questions, what version are you running your server and have this happened multiple times? For solutions, you can try killing the entities, if you provide the version I can send you the command for killing only Display Blocks

**Comment by GunsNHemps** [comment]
The version is 1.20.6

**Comment by Pozzoo** [comment]
You can use the following command to kill all DisplayBlock entities: "/kill @e[type=minecraft:block_display]". This should remove the ghost blocks

**Comment by GunsNHemps** [comment]
The command is saying: Error: Player not found. If i define myself as the player it will kil me. The ghost blocks are still there.

**Comment by GunsNHemps** [comment]
![image](https://github.com/Pozzoo/quickTreePlugin/assets/173932802/6c302151-f497-4299-90d1-8fb022cf9316)

**Comment by GunsNHemps** [comment]
I just found out that the commands of the plugin no longer work at all.

![image](https://github.com/Pozzoo/quickTreePlugin/assets/173932802/d7fb6f08-b87d-457a-b1b8-2c45cbca2ff7)

**Comment by Pozzoo** [comment]
Do you have a plugin that changes the command behaviour? And for now, quickTree doesn't contain any commands, the one I sent you is from the game itself.

**Comment by Pozzoo** [comment]
Hello again, I found that this may be caused by the essentials plugin, which changes the /kill behaviour. Try using this command instead: "/minecraft:kill @e[type=minecraft:block_display]"

**Comment by GunsNHemps** [comment]
Thank you so much, this worked for me!
